-- Reddit AI News Pipeline - Snowflake Setup
-- Run as ACCOUNTADMIN or SYSADMIN

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS REDDIT_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Database & Schemas
CREATE DATABASE IF NOT EXISTS REDDIT_AI_NEWS;
USE DATABASE REDDIT_AI_NEWS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- Raw Table
CREATE TABLE IF NOT EXISTS RAW.REDDIT_POSTS (
    post_id         VARCHAR(20),
    title           VARCHAR(1000),
    author          VARCHAR(100),
    score           INTEGER,
    num_comments    INTEGER,
    url             VARCHAR(2000),
    permalink       VARCHAR(500),
    created_utc     TIMESTAMP_NTZ,
    scraped_at      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    load_date       DATE DEFAULT CURRENT_DATE(),
    PRIMARY KEY (post_id, load_date)
);

-- Roles
CREATE ROLE IF NOT EXISTS LOADER_ROLE;
CREATE ROLE IF NOT EXISTS TRANSFORM_ROLE;
CREATE ROLE IF NOT EXISTS ANALYST_ROLE;

-- Warehouse Access
GRANT USAGE ON WAREHOUSE REDDIT_WH TO ROLE LOADER_ROLE;
GRANT USAGE ON WAREHOUSE REDDIT_WH TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE REDDIT_WH TO ROLE ANALYST_ROLE;

-- Database Access
GRANT USAGE ON DATABASE REDDIT_AI_NEWS TO ROLE LOADER_ROLE;
GRANT USAGE ON DATABASE REDDIT_AI_NEWS TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON DATABASE REDDIT_AI_NEWS TO ROLE ANALYST_ROLE;

-- LOADER_ROLE Permissions
GRANT USAGE ON SCHEMA RAW TO ROLE LOADER_ROLE;
GRANT INSERT, SELECT ON TABLE RAW.REDDIT_POSTS TO ROLE LOADER_ROLE;

-- TRANSFORM_ROLE Permissions
GRANT USAGE ON SCHEMA RAW TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE TRANSFORM_ROLE;
GRANT ALL ON SCHEMA STAGING TO ROLE TRANSFORM_ROLE;
GRANT ALL ON SCHEMA INTERMEDIATE TO ROLE TRANSFORM_ROLE;
GRANT ALL ON SCHEMA ANALYTICS TO ROLE TRANSFORM_ROLE;

-- ANALYST_ROLE Permissions
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS TO ROLE ANALYST_ROLE;

-- Grant Roles to User (update username as needed)
GRANT ROLE LOADER_ROLE TO USER kylefischer;
GRANT ROLE TRANSFORM_ROLE TO USER kylefischer;
GRANT ROLE ANALYST_ROLE TO USER kylefischer;
